<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite ignored="0" hostname="yaokaideMacBook-Pro.local" failures="0" tests="4" name="com.tester.cases.JingDongCPSTest" time="7.795" errors="3" timestamp="07 Feb 2020 05:35:51 GMT" skipped="0">
  <testcase classname="com.tester.cases.JingDongCPSTest" name="shop_info" time="1.287">
    <error message="{&quot;code&quot;: -1, &quot;data&quot;: null, &quot;msg&quot;: &quot;jd_cps: 其他异常错误: Traceback (most recent call last):\n  File \&quot;./utils/deco.py\&quot;, line 37, in wrapper\n    return func(*args, **kwargs)\n  File \&quot;./spider/jd_cps/jd_cps_api.py\&quot;, line 139, in get_shop_info\n    r = self.request(&#039;GET&#039;, url, params=params, headers=headers)\n  File \&quot;./spider/jd_cps/jd_cps_api.py\&quot;, line 46, in request\n    raise Exception(f&#039;jd_cps请求重试超过最大次数: content:{content}, status_code:{status_code}&#039;)\nException: jd_cps请求重试超过最大次数: content:{\&quot;code\&quot;:402}, status_code:200\n&quot;, &quot;start_time&quot;: 1581053682, &quot;end_time&quot;: 1581053683}
请求url：http://47.97.206.10/api/jd_cps/shop_info?shop_id=996822" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: {"code": -1, "data": null, "msg": "jd_cps: 其他异常错误: Traceback (most recent call last):\n  File \"./utils/deco.py\", line 37, in wrapper\n    return func(*args, **kwargs)\n  File \"./spider/jd_cps/jd_cps_api.py\", line 139, in get_shop_info\n    r = self.request('GET', url, params=params, headers=headers)\n  File \"./spider/jd_cps/jd_cps_api.py\", line 46, in request\n    raise Exception(f'jd_cps请求重试超过最大次数: content:{content}, status_code:{status_code}')\nException: jd_cps请求重试超过最大次数: content:{\"code\":402}, status_code:200\n", "start_time": 1581053682, "end_time": 1581053683}
请求url：http://47.97.206.10/api/jd_cps/shop_info?shop_id=996822
	at com.tester.cases.JingDongCPSTest.shop_info(JingDongCPSTest.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:282)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:83)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:114)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </error>
  </testcase> <!-- shop_info -->
  <testcase classname="com.tester.cases.JingDongCPSTest" name="shops" time="2.018">
    <error message="{&quot;code&quot;: -1, &quot;data&quot;: null, &quot;msg&quot;: &quot;jd_cps: 其他异常错误: Traceback (most recent call last):\n  File \&quot;./utils/deco.py\&quot;, line 37, in wrapper\n    return func(*args, **kwargs)\n  File \&quot;./spider/jd_cps/jd_cps_api.py\&quot;, line 127, in get_shops\n    r = self.request(&#039;POST&#039;, url, json=data, headers=headers)\n  File \&quot;./spider/jd_cps/jd_cps_api.py\&quot;, line 46, in request\n    raise Exception(f&#039;jd_cps请求重试超过最大次数: content:{content}, status_code:{status_code}&#039;)\nException: jd_cps请求重试超过最大次数: content:{\&quot;code\&quot;:402}, status_code:200\n&quot;, &quot;start_time&quot;: 1581053687, &quot;end_time&quot;: 1581053689}
请求url：http://47.97.206.10/api/jd_cps/shops?page_no=1&amp;page_size=20" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: {"code": -1, "data": null, "msg": "jd_cps: 其他异常错误: Traceback (most recent call last):\n  File \"./utils/deco.py\", line 37, in wrapper\n    return func(*args, **kwargs)\n  File \"./spider/jd_cps/jd_cps_api.py\", line 127, in get_shops\n    r = self.request('POST', url, json=data, headers=headers)\n  File \"./spider/jd_cps/jd_cps_api.py\", line 46, in request\n    raise Exception(f'jd_cps请求重试超过最大次数: content:{content}, status_code:{status_code}')\nException: jd_cps请求重试超过最大次数: content:{\"code\":402}, status_code:200\n", "start_time": 1581053687, "end_time": 1581053689}
请求url：http://47.97.206.10/api/jd_cps/shops?page_no=1&page_size=20
	at com.tester.cases.JingDongCPSTest.shops(JingDongCPSTest.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:282)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:83)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:114)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </error>
  </testcase> <!-- shops -->
  <testcase classname="com.tester.cases.JingDongCPSTest" name="shop_item" time="3.419">
    <error message="{&quot;code&quot;: -1, &quot;data&quot;: null, &quot;msg&quot;: &quot;jd_cps: 其他异常错误: Traceback (most recent call last):\n  File \&quot;./utils/deco.py\&quot;, line 37, in wrapper\n    return func(*args, **kwargs)\n  File \&quot;./spider/jd_cps/jd_cps_api.py\&quot;, line 154, in get_shop_item\n    r = self.request(&#039;GET&#039;, url, params=params, headers=headers)\n  File \&quot;./spider/jd_cps/jd_cps_api.py\&quot;, line 46, in request\n    raise Exception(f&#039;jd_cps请求重试超过最大次数: content:{content}, status_code:{status_code}&#039;)\nUnboundLocalError: local variable &#039;content&#039; referenced before assignment\n&quot;, &quot;start_time&quot;: 1581053683, &quot;end_time&quot;: 1581053687}
请求url：http://47.97.206.10/api/jd_cps/shop_item?shop_id=996822&amp;page_no=1&amp;page_size=20" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: {"code": -1, "data": null, "msg": "jd_cps: 其他异常错误: Traceback (most recent call last):\n  File \"./utils/deco.py\", line 37, in wrapper\n    return func(*args, **kwargs)\n  File \"./spider/jd_cps/jd_cps_api.py\", line 154, in get_shop_item\n    r = self.request('GET', url, params=params, headers=headers)\n  File \"./spider/jd_cps/jd_cps_api.py\", line 46, in request\n    raise Exception(f'jd_cps请求重试超过最大次数: content:{content}, status_code:{status_code}')\nUnboundLocalError: local variable 'content' referenced before assignment\n", "start_time": 1581053683, "end_time": 1581053687}
请求url：http://47.97.206.10/api/jd_cps/shop_item?shop_id=996822&page_no=1&page_size=20
	at com.tester.cases.JingDongCPSTest.shop_item(JingDongCPSTest.java:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:282)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:83)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:114)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </error>
  </testcase> <!-- shop_item -->
  <testcase classname="com.tester.cases.JingDongCPSTest" name="items" time="1.071"/>
</testsuite> <!-- com.tester.cases.JingDongCPSTest -->
